version: '3.8'
services:
  playwright-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env.dev
    environment:
      - CI=true
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results